### ISSUE TITLE
Tooltips crashes the editor

### ISSUE THREAD

**Issue by mathias234** [VitalElement/AvalonStudio#274]
If you have two objects with tooltips on them and switch from one to another before the tooltip dissapears it will crash when i tries to create the new tooltip

stacktrace

`   at Avalonia.Controls.ToolTip.ShowToolTip(Control control)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Throttle`1._.Propagate(IScheduler self, UInt64 currentid)
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass2_1`1.<Schedule>b__1()
   at Avalonia.Threading.DispatcherTimer.<>c__DisplayClass22_0.<RunOnce>b__0(Object s, EventArgs e)
   at Avalonia.Threading.DispatcherTimer.RaiseTick()
   at Avalonia.Threading.JobRunner.RunJobs()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Application.Run(ICloseable closable)
   at AvalonStudio.App.Main(String[] args) in C:\AvalonStudio\AvalonStudio\AvalonStudio\App.paml.cs:line 60`

**Comment by danwalmsley** [comment]
Tooltips rewritten so this issue should have gone.
