### ISSUE TITLE
OpenFileDialog crashes on GTK3 backend on Arch Linux

### ISSUE THREAD

**Issue by PFCKrutonium** [VitalElement/AvalonStudio#378]
@kekekeks (I was told to CC)
```
krutonium@HpArch:~/AvalonStudio/AvalonStudio/AvalonStudio/bin/Release/netcoreapp1.1$ dotnet AvalonStudio.dll

Unhandled Exception: System.ArgumentNullException: SafeHandle cannot be null.
Parameter name: pHandle
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Avalonia.Gtk3.SystemDialog.ShowDialog(String title, GtkWindow parent, GtkFileChooserAction action, Boolean multiselect, String initialFileName)
   at AvalonStudio.Controls.Standard.SolutionExplorer.SolutionExplorerViewModel.<OpenSolution>d__28.MoveNext() in /home/krutonium/AvalonStudio/AvalonStudio/AvalonStudio.Controls.Standard/SolutionExplorer/SolutionExplorerViewModel.cs:line 153
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Avalonia.Threading.JobRunner.RunJobs()
   at Avalonia.Gtk3.Gtk3Platform.<Signal>b__25_0()
   at Avalonia.Gtk3.Interop.GlibTimeout.Handler(IntPtr data)
   at Avalonia.Gtk3.Gtk3Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at AvalonStudio.App.Main(String[] args) in /home/krutonium/AvalonStudio/AvalonStudio/AvalonStudio/App.paml.cs:line 58
Aborted (core dumped)
```

**Comment by kekekeks** [comment]
You probably aren't passing the parent window or something like that.

**Comment by kekekeks** [comment]
I don't have an arch box nearby, so it's probably better if you run it under debugger and determine the exact where it crashes.

**Comment by danwalmsley** [comment]
Fixed.
