### ISSUE TITLE
AvalonStudio doesn't run

### ISSUE THREAD

**Issue by lontivero** [VitalElement/AvalonStudio#670]
After cloning and building AvalonStudio as is described in the README file, it throws and exception when we run the compiled AvalonStudio.dll file.

# Environment
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300/

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.200 [/usr/share/dotnet/sdk]
  2.1.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Branch and HEAD
```bash
lontivero:~/GitHub/AvalonStudio/AvalonStudio(develop)$ git branch
*develop

lontivero:~/GitHub/AvalonStudio/AvalonStudio(develop)$ git log -1 --oneline
f85738de (HEAD -> develop, origin/develop, origin/HEAD) HotFix: Fix Selawik font.
```

# Steps 
1. git clone https://github.com/VitalElement/AvalonStudio --recursive
2. cd AvalonStudio/
3. dotnet restore
4. dotnet build
5. cd AvalonStudio/bin/Debug/netcoreapp2.1/
6. dotnet AvalonStudio.dll

# Output
```
lontivero:~/GitHub/AvalonStudio/AvalonStudio/AvalonStudio/bin/Debug/netcoreapp2.1(develop)$ dotnet AvalonStudio.dll
(dotnet:20849): Gtk-CRITICAL **: 02:29:25.567: gtk_application_new: assertion 'application_id == NULL || g_application_id_is_valid (application_id)' failed
Error loading xaml at resm:Mabiavalon.DockNC.Themes.Controls.paml?assembly=Mabiavalon.DockNC
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri, Object rootInstance)
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded()
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Styling.ISetStyleParent.NotifyResourcesChanged(ResourcesChangedEventArgs e)
   at Avalonia.Styling.Styles.<.ctor>b__2_0(IStyle x)
   at Avalonia.Collections.AvaloniaListExtensions.<>c__DisplayClass1_0`1.<ForEachItem>g__Add|0(Int32 index, IList items)
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(IList t, Int32 index)
   at Portable.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at Portable.Xaml.XamlObjectWriterInternal.AddToCollectionIfAppropriate(XamlType xt, XamlMember xm, Object parent, Object obj, Object keyObj)
   at Portable.Xaml.XamlObjectWriterInternal.StoreAppropriatelyTypedValue(ObjectState state, MemberAndValue ms, Object obj, Object keyObj)
   at Portable.Xaml.XamlObjectWriterInternal.OnWriteEndObject()
   at Portable.Xaml.XamlWriterInternalBase.WriteEndObject()
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.LoadFromReader(XamlReader reader, AvaloniaXamlContext context, IAmbientProvider parentAmbientProvider)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Type type, Object rootInstance)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj)
   at AvalonStudio.App.Initialize() in /home/lontivero/GitHub/AvalonStudio/AvalonStudio/AvalonStudio/App.paml.cs:line 68
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider)
   at AvalonStudio.App.Main(String[] args) in /home/lontivero/GitHub/AvalonStudio/AvalonStudio/AvalonStudio/App.paml.cs:line 51
Could not convert object 'Template' (of type System.String) to {clr-namespace:Avalonia;assembly=Avalonia.Base}AvaloniaProperty: The type initializer for 'Mabiavalon.DockNC.Docking.Branch' threw an exception.
   at Portable.Xaml.XamlObjectWriterInternal.GetCorrectlyTypedValue(XamlMember xm, XamlType xt, Object value)
   at Portable.Xaml.XamlObjectWriterInternal.StoreAppropriatelyTypedValue(ObjectState state, MemberAndValue ms, Object obj, Object keyObj)
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.LoadFromReader(XamlReader reader, AvaloniaXamlContext context, IAmbientProvider parentAmbientProvider)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri, Object rootInstance)
The type initializer for 'Mabiavalon.DockNC.Docking.Branch' threw an exception.
   at System.Runtime.CompilerServices.RuntimeHelpers._RunClassConstructor(RuntimeType type)
   at Avalonia.AvaloniaPropertyRegistry.GetRegistered(Type type)
   at Avalonia.AvaloniaPropertyRegistry.FindRegistered(Type type, String name)
   at Avalonia.Markup.Xaml.Converters.AvaloniaPropertyTypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Portable.Xaml.XamlObjectWriterInternal.GetCorrectlyTypedValue(XamlMember xm, XamlType xt, Object value)
Field not found: 'Avalonia.Controls.Control.DataContextProperty'.
```

**Comment by danwalmsley** [comment]
Try the features/Docking branch.

**Comment by lontivero** [comment]
it works! Thank you.
