### ISSUE TITLE
Error loading xaml at...

### ISSUE THREAD

**Issue by nopara73** [VitalElement/AvalonStudio#673]
This did not happen previously. This happens since you migrated to .NET Core 2.1.  

It happens when you try to run the locally build binary (as described in the readme: `dotnet ./AvalonStudio.dll`) on Windows 10. I will try to figure out what's going on and report back.

```
Error loading xaml at resm:Mabiavalon.DockNC.Themes.Controls.paml?assembly=Mabiavalon.DockNC
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri, Object rootInstance)
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded()
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Styling.ISetStyleParent.NotifyResourcesChanged(ResourcesChangedEventArgs e)
   at Avalonia.Styling.Styles.<.ctor>b__2_0(IStyle x)
   at Avalonia.Collections.AvaloniaListExtensions.<>c__DisplayClass1_0`1.<ForEachItem>g__Add|0(Int32 index, IList items)
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(IList t, Int32 index)
   at Portable.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at Portable.Xaml.XamlObjectWriterInternal.AddToCollectionIfAppropriate(XamlType xt, XamlMember xm, Object parent, Object obj, Object keyObj)
   at Portable.Xaml.XamlObjectWriterInternal.StoreAppropriatelyTypedValue(ObjectState state, MemberAndValue ms, Object obj, Object keyObj)
   at Portable.Xaml.XamlObjectWriterInternal.OnWriteEndObject()
   at Portable.Xaml.XamlWriterInternalBase.WriteEndObject()
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.LoadFromReader(XamlReader reader, AvaloniaXamlContext context, IAmbientProvider parentAmbientProvider)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Type type, Object rootInstance)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj)
   at AvalonStudio.App.Initialize() in C:\Users\user\Desktop\AvalonStudio\AvalonStudio\AvalonStudio\App.paml.cs:line 68
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider)
   at AvalonStudio.App.Main(String[] args) in C:\Users\user\Desktop\AvalonStudio\AvalonStudio\AvalonStudio\App.paml.cs:line 51
Could not convert object 'Template' (of type System.String) to {clr-namespace:Avalonia;assembly=Avalonia.Base}AvaloniaProperty: The type initializer for 'Mabiavalon.DockNC.Docking.Branch' threw an exception.
   at Portable.Xaml.XamlObjectWriterInternal.GetCorrectlyTypedValue(XamlMember xm, XamlType xt, Object value)
   at Portable.Xaml.XamlObjectWriterInternal.StoreAppropriatelyTypedValue(ObjectState state, MemberAndValue ms, Object obj, Object keyObj)
   at Portable.Xaml.XamlObjectWriterInternal.OnWriteValue(Object value)
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.LoadFromReader(XamlReader reader, AvaloniaXamlContext context, IAmbientProvider parentAmbientProvider)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri, Object rootInstance)
The type initializer for 'Mabiavalon.DockNC.Docking.Branch' threw an exception.
   at System.Runtime.CompilerServices.RuntimeHelpers._RunClassConstructor(RuntimeType type)
   at Avalonia.AvaloniaPropertyRegistry.GetRegistered(Type type)
   at Avalonia.AvaloniaPropertyRegistry.FindRegistered(Type type, String name)
   at Avalonia.Markup.Xaml.Converters.AvaloniaPropertyTypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Portable.Xaml.XamlObjectWriterInternal.GetCorrectlyTypedValue(XamlMember xm, XamlType xt, Object value)
Field not found: 'Avalonia.Controls.Control.DataContextProperty'.
   at Mabiavalon.DockNC.Docking.Branch..cctor()
```

**Comment by danwalmsley** [comment]
Sorry about this, there was a dependency that lost compatibility with latest Avalonia, and since the new Docking system is almost ready it wasn't worth fixing this. I'll merge Docking shortly to develop
