### ISSUE TITLE
Crash when clicking on the run button of the default Avalonia net core project

### ISSUE THREAD

**Issue by pikachuk** [VitalElement/AvalonStudio#704]
Hello, I wanted to test AvalonStudio so i've created a project using the default template for a .net core project using Avalonia UI and built it in order to see the result, the build succeeded so I clicked on the run button and it ended up making avalon studio crash
Since the project is still in early stages, I know that crashes are to be expected, so I'm sharing the log in order to help fixing it, so here is the log

> Unhandled Exception: System.TimeoutException: .NET core load awaiting timed out for 00:00:30
>    at Microsoft.Samples.Debugging.CorDebug.CoreClrShimUtil.CreateCorDebugImpl(DbgShimInterop dbgShimInterop, UInt32 processId, TimeSpan runtimeLoadTimeout, Void* resumeHandle, Action`2 onSetup) in /home/pikachuk/AvalonStudio/debugger-libs/CorApi2/debug/CoreClrShimUtil.cs:line 114
>    at Microsoft.Samples.Debugging.CorDebug.CoreClrShimUtil.CreateCorDebugForCommand(DbgShimInterop dbgShimInterop, String command, String workingDir, IDictionary`2 env, TimeSpan runtimeLoadTimeout, Action`2 onSetup, UInt32& procId) in /home/pikachuk/AvalonStudio/debugger-libs/CorApi2/debug/CoreClrShimUtil.cs:line 52
>    at Mono.Debugging.Win32.CoreClrDebuggerSession.<>c__DisplayClass3_0.<OnRun>b__0() in /home/pikachuk/AvalonStudio/debugger-libs/Mono.Debugging.Win32/CoreClrDebuggerSession.cs:line 37
>    at Mono.Debugging.Win32.MtaThread.Run(Action ts, Int32 timeout) in /home/pikachuk/AvalonStudio/debugger-libs/Mono.Debugging.Win32/MtaThread.cs:line 83
>    at Mono.Debugging.Win32.CoreClrDebuggerSession.OnRun(DebuggerStartInfo startInfo) in /home/pikachuk/AvalonStudio/debugger-libs/Mono.Debugging.Win32/CoreClrDebuggerSession.cs:line 39
>    at Mono.Debugging.Client.DebuggerSession.<>c__DisplayClass96_0.<Run>b__0() in /home/pikachuk/AvalonStudio/debugger-libs/Mono.Debugging/Mono.Debugging.Client/DebuggerSession.cs:line 342
>    at Mono.Debugging.Client.DebuggerSession.<Dispatch>b__95_0(Object <p0>) in /home/pikachuk/AvalonStudio/debugger-libs/Mono.Debugging/Mono.Debugging.Client/DebuggerSession.cs:line 305
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
> /usr/bin/AvalonStudio.sh : ligne 1 : 28209 Abandon                 (core dumped)dotnet $AVALONSTUDIOPATH/AvalonStudio.dll
>

**Comment by danwalmsley** [comment]
@Krutonium did you get this to run on Arch?

**Comment by Krutonium** [comment]
![works](https://user-images.githubusercontent.com/3945538/47203858-ab066400-d34f-11e8-8d94-cc324ec7799e.png)

I'm able to run it without problems (latest commit) on Arch Linux.

**Comment by pikachuk** [comment]
I was using KDE Plasma if it may be the problem

**Comment by Krutonium** [comment]
I can't get Plasma running on here to test that.

**Comment by aaronfranke** [comment]
I have the same problem on Ubuntu 18.04, with DotNet Core 2.1.500. When I create a new project and try to run it, this happens:

    LTTng-UST: Error (-17) while registering tracepoint probe. Duplicate registration of tracepoint probes having the same name is not allowed.
    Aborted (core dumped)

Full log:

```
$ ./AvalonStudio 

(AvalonStudio:6769): Gtk-CRITICAL **: 02:05:55.187: gtk_application_new: assertion 'application_id == NULL || g_application_id_is_valid (application_id)' failed

(AvalonStudio:6769): Gtk-CRITICAL **: 02:05:58.357: gtk_window_resize: assertion 'width > 0' failed
Gtk-Message: 02:06:01.508: GtkDialog mapped without a transient parent. This is discouraged.

(AvalonStudio:6769): GLib-GObject-CRITICAL **: 02:06:05.290: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed

(AvalonStudio:6769): GLib-GObject-WARNING **: 02:06:05.291: instance with invalid (NULL) class pointer

(AvalonStudio:6769): GLib-GObject-CRITICAL **: 02:06:05.291: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(AvalonStudio:6769): GLib-GObject-WARNING **: 02:06:05.291: instance with invalid (NULL) class pointer

(AvalonStudio:6769): GLib-GObject-CRITICAL **: 02:06:05.291: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Gtk-Message: 02:06:07.925: GtkDialog mapped without a transient parent. This is discouraged.

(AvalonStudio:6769): GLib-GObject-CRITICAL **: 02:06:12.169: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed

(AvalonStudio:6769): GLib-GObject-WARNING **: 02:06:12.169: instance with invalid (NULL) class pointer

(AvalonStudio:6769): GLib-GObject-CRITICAL **: 02:06:12.169: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(AvalonStudio:6769): GLib-GObject-WARNING **: 02:06:12.169: instance with invalid (NULL) class pointer

(AvalonStudio:6769): GLib-GObject-CRITICAL **: 02:06:12.169: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Automatically selecting netcoreapp2.1 as TargetFramework
LTTng-UST: Error (-17) while registering tracepoint probe. Duplicate registration of tracepoint probes having the same name is not allowed.
Aborted (core dumped)
```

**Comment by Gaojianli** [comment]
@Krutonium Could you please tell me how did you install AvalonStudio on Arch?
I tried to use debtap to convert the deb into tar.xz and install it on my arch, but when i try i to run it, it stuck, and there was no error, no log.
Just like this:
![image](https://user-images.githubusercontent.com/19235246/68591508-df554100-04cb-11ea-8fc1-6524a49237c0.png)
