### ISSUE TITLE
[Ubuntu] Crash when opening "new solution" window

### ISSUE THREAD

**Issue by JkFrcss** [VitalElement/AvalonStudio#709]
After clicking on "new solution" button on start page, "new solution" window fails to render and after few seconds AvalonStudio crashes. Using AvalonStudio from "develop" branch

basic system info:
-Ubuntu 18.04 LTS 64bit
-MATE desktop enviroment 1.20.1
-kernel 4.20rc4

log:

> Unhandled Exception: System.InvalidOperationException: Failed to create Skia render target surface
   at Avalonia.Skia.SurfaceRenderTarget..ctor(CreateInfo createInfo)
   at Avalonia.Skia.DrawingContextImpl.CreateRenderTarget(Size size, Nullable`1 format)
   at Avalonia.Skia.DrawingContextImpl.CreateLayer(Size size)
   at Avalonia.Rendering.RenderLayers.Update(Scene scene, IDrawingContextImpl context)
   at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(Func`1 contextFactory, Boolean recursiveCall)
   at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite)
   at Avalonia.Controls.TopLevel.HandlePaint(Rect rect)
   at Avalonia.Gtk3.WindowBaseImpl.OnDraw(IntPtr gtkwidget, IntPtr cairocontext, IntPtr userdata)
   at Avalonia.Gtk3.Gtk3Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Application.Run(Window mainWindow)
   at AvalonStudio.Shell.Shell.StartShellApp[TAppBuilder,TMainWindow](TAppBuilder builder, String appName, IDockFactory layoutFactory, Func`1 dataContextProvider) in /home/jakov/AvalonStudio/AvalonStudio.Shell/src/AvalonStudio.Shell/Shell.cs:line 14
   at AvalonStudio.App.Main(String[] args) in /home/jakov/AvalonStudio/AvalonStudio/AvalonStudio/App.paml.cs:line 44
Prekinut (jezgra izbačena)

screenshot before crash:
![screenshot at 2018-11-29 20-17-50](https://user-images.githubusercontent.com/36544783/49247076-b3ee5900-f416-11e8-9f60-d737c01298f4.png)

edit:
fixed typo

**Comment by mrdev023** [comment]
Same issue

**Comment by JkFrcss** [comment]
This is Avalonia UI related issue. So I will close this issue

**Comment by JkFrcss** [comment]
Update:

Found temporary solution for this issue

Needed file changes:
- Change `<AvaloniaVersion>0.7.1-build782-beta</AvaloniaVersion>` line in file `AvaloniaStudio/Directory.Build.targets` to `<AvaloniaVersion>0.7.1-build712-beta</AvaloniaVersion>`  


- Change  `<AvaloniaVersion>0.7.1-build782-beta</AvaloniaVersion>` line in file `AvalonStudio/AvalonStudio.Shell/src/Versions.props` to `<AvaloniaVersion>0.7.1-build712-beta</AvaloniaVersion>`

then build AvalonStudio again, and it should work.

After this AvalonStudio will use older version of Avalonia UI that does not have this issue.
