### ISSUE TITLE
Could not load file or assembly AvalonStudio.Controls.Standard

### ISSUE THREAD

**Issue by AlessandroMiorelli** [VitalElement/AvalonStudio#720]
Hi, if I execute that
D:\AvalonStudio\AvalonStudio\AvalonStudio\AvalonStudio\bin\Debug\netcoreapp2.2>dotnet ./AvalonStudio.dll

I have this error:

Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'AvalonStudio.Controls.Standard, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark, IntPtr pPrivHostBinder)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(String name)
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetResAsmAndPath(Uri uri)
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(Uri uri)
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(Uri uri, Uri baseUri)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri, Object rootInstance)
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded()
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Styling.ISetStyleParent.NotifyResourcesChanged(ResourcesChangedEventArgs e)
   at Avalonia.Styling.Styles.<.ctor>b__4_0(IStyle x)
   at Avalonia.Collections.AvaloniaListExtensions.<>c__DisplayClass0_0`1.<ForEachItem>b__0(Int32 _, T i)
   at Avalonia.Collections.AvaloniaListExtensions.<>c__DisplayClass1_0`1.<ForEachItem>g__Add|0(Int32 index, IList items)
   at Avalonia.Collections.AvaloniaListExtensions.<>c__DisplayClass1_0`1.<ForEachItem>b__2(Object _, NotifyCollectionChangedEventArgs e)
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(IList t, Int32 index)
   at Avalonia.Collections.AvaloniaList`1.Add(T item)
   at Avalonia.Styling.Styles.Add(IStyle item)
   at AvalonStudio.App.!XamlIlPopulate(IServiceProvider , App ) in AvalonStudio.App.paml:line 23
   at AvalonStudio.App.!XamlIlPopulateTrampoline(App )
   at AvalonStudio.App.Initialize() in D:\AvalonStudio\AvalonStudio\AvalonStudio\AvalonStudio\App.paml.cs:line 99
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider)
   at AvalonStudio.Shell.Shell.StartShellApp[TAppBuilder,TMainWindow](TAppBuilder builder, String appName, IDockFactory layoutFactory, Func`1 dataContextProvider) in D:\AvalonStudio\AvalonStudio\AvalonStudio.Shell\src\AvalonStudio.Shell\Shell.cs:line 15
   at AvalonStudio.App.Main(String[] args) in D:\AvalonStudio\AvalonStudio\AvalonStudio\AvalonStudio\App.paml.cs:line 47

But I have AvalonStudio.Controls.Standard.dll in AvalonStudio\AvalonStudio.Controls.Standard\bin\Debug\netstandard2.0

What should I do?

Regards
Alessandro

**Comment by danwalmsley** [comment]
Thanks for the report I will get this fixed asap.

**Comment by danwalmsley** [comment]
fixed now.
