### ISSUE TITLE
Run on Raspbian

### ISSUE THREAD

**Issue by scout208** [VitalElement/AvalonStudio#733]
Hi, has anyone been able to get this to run on a Raspberry Pi running Raspbian? I tried following the readme instructions but I'm getting this error: 

````
$ dotnet ./AvalonStudio.dll
libEGL warning: DRI2: failed to authenticate
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'AvalonStudio.Controls.Standard, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'AvalonStudio.Controls.Standard, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(String name)
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetResAsmAndPath(Uri uri)
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(Uri uri)
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(Uri uri, Uri baseUri)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri)
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded()
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Styling.ISetStyleParent.NotifyResourcesChanged(ResourcesChangedEventArgs e)
   at Avalonia.Styling.Styles.<.ctor>b__4_0(IStyle x)
   at Avalonia.Collections.AvaloniaListExtensions.<>c__DisplayClass0_0`1.<ForEachItem>b__0(Int32 _, T i)
   at Avalonia.Collections.AvaloniaListExtensions.<>c__DisplayClass1_0`1.<ForEachItem>g__Add|0(Int32 index, IList items)
   at Avalonia.Collections.AvaloniaListExtensions.<>c__DisplayClass1_0`1.<ForEachItem>b__2(Object _, NotifyCollectionChangedEventArgs e)
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index)
   at Avalonia.Collections.AvaloniaList`1.Add(T item)
   at Avalonia.Styling.Styles.Add(IStyle item)
   at AvalonStudio.App.!XamlIlPopulate(IServiceProvider , App ) in AvalonStudio.App.paml:line 23
   at AvalonStudio.App.!XamlIlPopulateTrampoline(App )
   at AvalonStudio.App.Initialize() in /home/pi/AvalonStudio/AvalonStudio/AvalonStudio/App.paml.cs:line 29
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at AvalonStudio.Shell.Shell.StartShellApp[TAppBuilder](TAppBuilder builder, String appName, ShellAppMainDelegate main, String[] args, IFactory layoutFactory) in /home/pi/AvalonStudio/AvalonStudio.Shell/src/AvalonStudio.Shell/Shell.cs:line 17
   at AvalonStudio.Program.Main(String[] args) in /home/pi/AvalonStudio/AvalonStudio/AvalonStudio/Program.cs:line 34


Aborted
````

**Comment by CreateLab** [comment]
mb it's help to you, but some years ago avalonia normaly works only on ubuntu mate for rpi
try it

**Comment by enderger** [comment]
Try re-downloading AvalonStudio, something seems off about this issue.
