### ISSUE TITLE
[Error] The program crashes when clicking on the project files window. [Ubuntu 20.04]

### ISSUE THREAD

**Issue by Anderson0xFF** [VitalElement/AvalonStudio#754]
`Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Collections.ObjectModel.Collection`1.System.Collections.IList.get_Item(Int32 index)
   at Avalonia.Controls.SelectionModel.<>c.<get_SelectedItems>b__39_1(List`1 infos, Int32 index)
   at Avalonia.Controls.SelectionModel.get_SelectedItem()
   at Avalonia.Controls.Primitives.SelectingItemsControl.OnSelectionModelSelectionChanged(Object sender, SelectionModelSelectionChangedEventArgs e)
   at Avalonia.Controls.SelectionModel.OnSelectionChanged(SelectionModelSelectionChangedEventArgs e)
   at Avalonia.Controls.SelectionModel.OnSelectionInvalidatedDueToCollectionChange(Boolean selectionInvalidated, IReadOnlyList`1 removedItems)
   at Avalonia.Controls.SelectionNode.OnSourceListChanged(Object dataSource, NotifyCollectionChangedEventArgs args)
   at Avalonia.Controls.ItemsSourceView.OnItemsSourceChanged(NotifyCollectionChangedEventArgs args)
   at Avalonia.Controls.ItemsSourceView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at Dock.Model.FactoryBase.AddDockable(IDock dock, IDockable dockable)
   at AvalonStudio.Shell.DockExtensions.Dock(IDock dock, IDockableViewModel model, Boolean add) in /home/anderson/AvalonStudio/AvalonStudio.Shell/src/AvalonStudio.Shell/DockExtensions.cs:line 100
   at AvalonStudio.Shell.ShellViewModel.AddDocument(IDocumentTabViewModel document, Boolean temporary, Boolean select) in /home/anderson/AvalonStudio/AvalonStudio.Shell/src/AvalonStudio.Shell/ShellViewModel.cs:line 278
   at AvalonStudio.Shell.IShellExtensions.AddOrSelectDocument[T](IShell me, T document) in /home/anderson/AvalonStudio/AvalonStudio.Shell/src/AvalonStudio.Shell.Extensibility/Shell/IShellExtensions.cs:line 20
   at AvalonStudio.Studio.StudioViewModel.OpenDocumentAsync(ISourceFile file) in /home/anderson/AvalonStudio/AvalonStudio/AvalonStudio.Studio/StudioViewModel.cs:line 336
   at AvalonStudio.Studio.StudioViewModel.OpenDocumentAsync(ISourceFile file, Int32 line, Int32 startColumn, Int32 endColumn, Boolean debugHighlight, Boolean selectLine, Boolean focus) in /home/anderson/AvalonStudio/AvalonStudio/AvalonStudio.Studio/StudioViewModel.cs:line 346
   at AvalonStudio.Controls.Standard.SolutionExplorer.SolutionExplorerViewModel.<>c.<<-ctor>b__7_2>d.MoveNext() in /home/anderson/AvalonStudio/AvalonStudio/AvalonStudio.Controls.Standard/SolutionExplorer/SolutionExplorerViewModel.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass8_0.<Post>b__0()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken)
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at AvalonStudio.Shell.Shell.StartShellApp[TAppBuilder](TAppBuilder builder, String appName, ShellAppMainDelegate main, String[] args, IFactory layoutFactory) in /home/anderson/AvalonStudio/AvalonStudio.Shell/src/AvalonStudio.Shell/Shell.cs:line 17
   at AvalonStudio.Program.Main(String[] args) in /home/anderson/AvalonStudio/AvalonStudio/AvalonStudio/Program.cs:line 32
`

**Comment by mate1213** [comment]
Hi!
I found this error too.
There is some previous version where this IDE not crashing on this event, or some "hack" with can solve this (ex: some other way for open file)? 
Thanks for help!

**Comment by imaxs** [comment]
it's a trash project...

**Comment by Thaval** [comment]
@imaxs So I assume you can do it better? Despite of that, you shouldn't be that disrespectful.

**Comment by imaxs** [comment]
> @imaxs So I assume you can do it better? Despite of that, you shouldn't be that disrespectful.

 This is my point of view. It's not up to you to decide what everyone should do or be.

**Comment by FlaviusHouk** [comment]
You can update version of Avalonia libraries in both ./Directory.Build.Targets and ./AvalonStudio.Shell/src/Versions.props to 0.10.0-preview4. It'll fix the problem.

**Comment by najlot** [comment]
Avalonia was updated to 0.10.0, so the error should be fixed.
@Tekadon58 :
Can the issue be closed?

**Comment by Anderson0xFF** [comment]
> Avalonia was updated to 0.10.0, so the error should be fixed.
> @Tekadon58 :
> Can the issue be closed?

I haven't tested it but it can close the issue.
