### ISSUE TITLE
Unable to install AvalonStudio with ubuntu20.04LTS

### ISSUE THREAD

**Issue by tousei-seiso** [VitalElement/AvalonStudio#760]
kubuntu 20.04LTS.

Following the installing instruction ['Building from source'.](https://github.com/VitalElement/AvalonStudio#building-from-source), I created a locally built binary and execute it.
Unhandled exception occured as below.

> ./AvalonStudio`
Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl)
   at Avalonia.Media.FontManager.get_Current()
   at Avalonia.Rendering.RendererBase..ctor(Boolean useManualFpsCounting)
   at Avalonia.Rendering.DeferredRenderer..ctor(IRenderRoot root, IRenderLoop renderLoop, ISceneBuilder sceneBuilder, IDispatcher dispatcher, IDeferredRendererLock rendererLock)
   at Avalonia.X11.X11Window.CreateRenderer(IRenderRoot root)
   at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl)
   at Avalonia.Controls.Window..ctor(IWindowImpl impl)
   at Avalonia.Controls.Window..ctor()
   at AvalonStudio.Shell.Controls.MetroWindow..ctor() in /home/osamu/prj/AvalonStudio/AvalonStudio.Shell/src/AvalonStudio.Shell/Controls/MetroWindow.cs:line 63
   at AvalonStudio.MainWindow..ctor() in /home/osamu/prj/AvalonStudio/AvalonStudio/AvalonStudio/MainWindow.xaml.cs:line 15
   at AvalonStudio.App.OnFrameworkInitializationCompleted() in /home/osamu/prj/AvalonStudio/AvalonStudio/AvalonStudio/App.paml.cs:line 18
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at AvalonStudio.Shell.Shell.StartShellApp[TAppBuilder](TAppBuilder builder, String appName, ShellAppMainDelegate main, String[] args, IFactory layoutFactory) in /home/osamu/prj/AvalonStudio/AvalonStudio.Shell/src/AvalonStudio.Shell/Shell.cs:line 17
   at AvalonStudio.Program.Main(String[] args) in /home/osamu/prj/AvalonStudio/AvalonStudio/AvalonStudio/Program.cs:line 32
Aborted(Core dump)

Next, following '[Build AvalonStudio on Ubuntu 18.04](https://secanablog.wordpress.com/2018/05/24/build-avalonstudio-on-ubuntu-18-04/)', I proceeded step by step up to './build.sh'.
But the result of './build.sh' is error like below:

> Analyzing build script...
Processing build script...
Installing tools...
Installing addins...
Compiling build script...
Error: The assembly name is invalid.

Failed both try.
Is AvalonStudio able to install to ubuntu20.04LTS?
Is there anyway to install AvalonStudio without an error?

**Comment by najlot** [comment]
Hello @tousei-seiso,
can you please try it with
https://vitalelement.visualstudio.com/8a67f0f6-b558-45b8-9f04-578798903575/_apis/build/builds/858/artifacts?artifactName=drop&api-version=6.0&%24format=zip
thank you
