### ISSUE TITLE
Crash opening Program.cs in new console app in Mint 20 (Ubuntu 20.04)

### ISSUE THREAD

**Issue by ghost** [VitalElement/AvalonStudio#762]
command line:
IDE start:
----------------------
username@computername:~/Git/AvalonStudio/AvalonStudio/AvalonStudio/bin/Debug/netcoreapp3.1$ ./AvalonStudio
radeon: Failed to get PCI ID, error number -13
---------

...
create or open solution
...

-------
Automatically selecting netcoreapp2.1 as TargetFramework
----------

...
select/open cs file:

...
----------
Automatically selecting netcoreapp2.1 as TargetFramework
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Collections.ObjectModel.Collection`1.System.Collections.IList.get_Item(Int32 index)
   at Avalonia.Controls.SelectionModel.<>c.<get_SelectedItems>b__39_1(List`1 infos, Int32 index)
   at Avalonia.Controls.SelectionModel.get_SelectedItem()
   at Avalonia.Controls.Primitives.SelectingItemsControl.OnSelectionModelSelectionChanged(Object sender, SelectionModelSelectionChangedEventArgs e)
   at Avalonia.Controls.SelectionModel.OnSelectionChanged(SelectionModelSelectionChangedEventArgs e)
   at Avalonia.Controls.SelectionModel.OnSelectionInvalidatedDueToCollectionChange(Boolean selectionInvalidated, IReadOnlyList`1 removedItems)
   at Avalonia.Controls.SelectionNode.OnSourceListChanged(Object dataSource, NotifyCollectionChangedEventArgs args)
   at Avalonia.Controls.ItemsSourceView.OnItemsSourceChanged(NotifyCollectionChangedEventArgs args)
   at Avalonia.Controls.ItemsSourceView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at Dock.Model.FactoryBase.AddDockable(IDock dock, IDockable dockable)
   at AvalonStudio.Shell.DockExtensions.Dock(IDock dock, IDockableViewModel model, Boolean add) in /home/username/Git/AvalonStudio/AvalonStudio.Shell/src/AvalonStudio.Shell/DockExtensions.cs:line 100
   at AvalonStudio.Shell.ShellViewModel.AddDocument(IDocumentTabViewModel document, Boolean temporary, Boolean select) in /home/username/Git/AvalonStudio/AvalonStudio.Shell/src/AvalonStudio.Shell/ShellViewModel.cs:line 278
   at AvalonStudio.Shell.IShellExtensions.AddOrSelectDocument[T](IShell me, T document) in /home/username/Git/AvalonStudio/AvalonStudio.Shell/src/AvalonStudio.Shell.Extensibility/Shell/IShellExtensions.cs:line 20
   at AvalonStudio.Studio.StudioViewModel.OpenDocumentAsync(ISourceFile file) in /home/username/Git/AvalonStudio/AvalonStudio/AvalonStudio.Studio/StudioViewModel.cs:line 336
   at AvalonStudio.Studio.StudioViewModel.OpenDocumentAsync(ISourceFile file, Int32 line, Int32 startColumn, Int32 endColumn, Boolean debugHighlight, Boolean selectLine, Boolean focus) in /home/username/Git/AvalonStudio/AvalonStudio/AvalonStudio.Studio/StudioViewModel.cs:line 346
   at AvalonStudio.Controls.Standard.SolutionExplorer.SolutionExplorerViewModel.<>c.<<-ctor>b__7_2>d.MoveNext() in /home/username/Git/AvalonStudio/AvalonStudio/AvalonStudio.Controls.Standard/SolutionExplorer/SolutionExplorerViewModel.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass8_0.<Post>b__0()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at AvalonStudio.Shell.Shell.StartShellApp[TAppBuilder](TAppBuilder builder, String appName, ShellAppMainDelegate main, String[] args, IFactory layoutFactory) in /home/username/Git/AvalonStudio/AvalonStudio.Shell/src/AvalonStudio.Shell/Shell.cs:line 17
   at AvalonStudio.Program.Main(String[] args) in /home/username/Git/AvalonStudio/AvalonStudio/AvalonStudio/Program.cs:line 32
Aborted (core dumped)
username@computername:~/Git/AvalonStudio/AvalonStudio/AvalonStudio/bin/Debug/netcoreapp3.1$ 
---------------------------------------
sys info:

[https://termbin.com/bo9n](https://termbin.com/bo9n)

**Comment by ghost** [comment]
Hi! Currently, everyone can use only .NET Core 3.1 & .NET 6 for LTS.
