### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by WholesomeIsland** [VitalElement/AvalonStudio#763]
Every time I try to open a project and create a file it crashes. I have tested this on both Linux and Windows 10 with the same stack trace. here is it below,

```
Automatically selecting netcoreapp3.0 as TargetFramework
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Collections.ObjectModel.Collection`1.System.Collections.IList.get_Item(Int32 index)
   at Avalonia.Controls.SelectionModel.<>c.<get_SelectedItems>b__39_1(List`1 infos, Int32 index)
   at Avalonia.Controls.SelectedItems`2.get_Item(Int32 index)
   at Avalonia.Controls.SelectionModel.get_SelectedItem()
   at Avalonia.Controls.Primitives.SelectingItemsControl.OnSelectionModelSelectionChanged(Object sender, SelectionModelSelectionChangedEventArgs e)
   at Avalonia.Controls.SelectionModel.OnSelectionChanged(SelectionModelSelectionChangedEventArgs e)
   at Avalonia.Controls.SelectionModel.OnSelectionInvalidatedDueToCollectionChange(Boolean selectionInvalidated, IReadOnlyList`1 removedItems)
   at Avalonia.Controls.SelectionNode.OnSourceListChanged(Object dataSource, NotifyCollectionChangedEventArgs args)
   at Avalonia.Controls.ItemsSourceView.OnItemsSourceChanged(NotifyCollectionChangedEventArgs args)
   at Avalonia.Controls.ItemsSourceView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at Dock.Model.FactoryBase.AddDockable(IDock dock, IDockable dockable)
   at AvalonStudio.Shell.DockExtensions.Dock(IDock dock, IDockableViewModel model, Boolean add) in C:\Users\spinn\OneDrive\AvalonStudio\AvalonStudio.Shell\src\AvalonStudio.Shell\DockExtensions.cs:line 100
   at AvalonStudio.Shell.ShellViewModel.AddDocument(IDocumentTabViewModel document, Boolean temporary, Boolean select) in C:\Users\spinn\OneDrive\AvalonStudio\AvalonStudio.Shell\src\AvalonStudio.Shell\ShellViewModel.cs:line 278
   at AvalonStudio.Shell.IShellExtensions.AddOrSelectDocument[T](IShell me, T document) in C:\Users\spinn\OneDrive\AvalonStudio\AvalonStudio.Shell\src\AvalonStudio.Shell.Extensibility\Shell\IShellExtensions.cs:line 20
   at AvalonStudio.Studio.StudioViewModel.OpenDocumentAsync(ISourceFile file) in C:\Users\spinn\OneDrive\AvalonStudio\AvalonStudio\AvalonStudio.Studio\StudioViewModel.cs:line 336
   at AvalonStudio.Studio.StudioViewModel.OpenDocumentAsync(ISourceFile file, Int32 line, Int32 startColumn, Int32 endColumn, Boolean debugHighlight, Boolean selectLine, Boolean focus) in C:\Users\spinn\OneDrive\AvalonStudio\AvalonStudio\AvalonStudio.Studio\StudioViewModel.cs:line 346
   at AvalonStudio.Controls.Standard.SolutionExplorer.SolutionExplorerViewModel.<>c.<<-ctor>b__7_4>d.MoveNext() in C:\Users\spinn\OneDrive\AvalonStudio\AvalonStudio\AvalonStudio.Controls.Standard\SolutionExplorer\SolutionExplorerViewModel.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass8_0.<Post>b__0()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at AvalonStudio.Shell.Shell.StartShellApp[TAppBuilder](TAppBuilder builder, String appName, ShellAppMainDelegate main, String[] args, IFactory layoutFactory) in C:\Users\spinn\OneDrive\AvalonStudio\AvalonStudio.Shell\src\AvalonStudio.Shell\Shell.cs:line 17
   at AvalonStudio.Program.Main(String[] args) in C:\Users\spinn\OneDrive\AvalonStudio\AvalonStudio\AvalonStudio\Program.cs:line 32
```

**Comment by WholesomeIsland** [comment]
this is sort of a duplacate of #762 but i did this with a console app and i get the same error with an avolania app.
